version: '3'
services:
  backend:
    build: .
    ports:
    - 8000:80
    volumes:
    - ../:/var/www/html
  mysql:
    image: 'mysql:5.7'
    ports:
      - 3600:3306
    environment:
      MYSQL_ROOT_PASSWORD: exemplo